#############
#这是3-1小节的课后作业第1题
#############
"""
尝试使用各个函数：
想想可存储到列表中的东西，
如山岳、河流、国家、城市、语言或你喜欢的任何东西。
编写一个程序，
在其中创建一个包含这些元素的列表，
然后，
对于本章介绍的每个函数，
都至少使用一次来处理这个列表。
"""
##
#
## 列表函数
#
##

place = ['xi an','fu zhou','bei jing','shang hai','qing dao']
print("原始列表：")
print(place)
print("临时升序列表：")
print(sorted(place))
print("原始列表：")
print(place)
print("临时降序列表：")
print(sorted(place,reverse=True))
print("原始列表：")
print(place)
place.reverse()
print("翻转列表：")
print(place)
place.reverse()
print("再次翻转列表：")
print(place)
place.sort()
print("升序列表：")
print(place)
place.sort(reverse=True)
print("降序列表：")
print(place)
print("列表长度：")
print(len(place))
