from random import randint
class Die():
    def __init__(self,sides=6):
        self.sides = sides
    def roll_die(self):
        num = randint(1,self.sides)
        print(num)
print("6面骰子点数：")
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
num = Die(6)
num.roll_die()
print("10面骰子点数：")
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
num = Die(10)
num.roll_die()
print("20面骰子点数：")
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()
num = Die(20)
num.roll_die()